
# Messages
OnlyPlayer: "&cOva komanda je namenjena samo igraÄima!"
NoLocation: "&6Lokacija nije postavljena" 
Teleported: "&6Teleportovani ste"
LocationSet: "&6Lokacija postavljena" 
CommandUsage: "&a/game start - /game setlocation" 